/**
 * Onboarding Constants for Continuum Enterprise
 * Contains all static data for the 9-step onboarding wizard
 */

import type {
  LeaveTypeConfig,
  RoleConfig,
  ConstraintConfig,
  CompanySize,
  FiscalYearMonth,
  IndianState,
  Industry,
  CompanySizeOption,
  FiscalYearOption,
  TimezoneOption,
} from './types';

// ─── Indian States and Union Territories ──────────────────────────────────────

export const INDIAN_STATES: IndianState[] = [
  { code: 'AN', name: 'Andaman and Nicobar Islands' },
  { code: 'AP', name: 'Andhra Pradesh' },
  { code: 'AR', name: 'Arunachal Pradesh' },
  { code: 'AS', name: 'Assam' },
  { code: 'BR', name: 'Bihar' },
  { code: 'CH', name: 'Chandigarh' },
  { code: 'CT', name: 'Chhattisgarh' },
  { code: 'DN', name: 'Dadra and Nagar Haveli and Daman and Diu' },
  { code: 'DL', name: 'Delhi' },
  { code: 'GA', name: 'Goa' },
  { code: 'GJ', name: 'Gujarat' },
  { code: 'HR', name: 'Haryana' },
  { code: 'HP', name: 'Himachal Pradesh' },
  { code: 'JK', name: 'Jammu and Kashmir' },
  { code: 'JH', name: 'Jharkhand' },
  { code: 'KA', name: 'Karnataka' },
  { code: 'KL', name: 'Kerala' },
  { code: 'LA', name: 'Ladakh' },
  { code: 'LD', name: 'Lakshadweep' },
  { code: 'MP', name: 'Madhya Pradesh' },
  { code: 'MH', name: 'Maharashtra' },
  { code: 'MN', name: 'Manipur' },
  { code: 'ML', name: 'Meghalaya' },
  { code: 'MZ', name: 'Mizoram' },
  { code: 'NL', name: 'Nagaland' },
  { code: 'OR', name: 'Odisha' },
  { code: 'PY', name: 'Puducherry' },
  { code: 'PB', name: 'Punjab' },
  { code: 'RJ', name: 'Rajasthan' },
  { code: 'SK', name: 'Sikkim' },
  { code: 'TN', name: 'Tamil Nadu' },
  { code: 'TG', name: 'Telangana' },
  { code: 'TR', name: 'Tripura' },
  { code: 'UP', name: 'Uttar Pradesh' },
  { code: 'UK', name: 'Uttarakhand' },
  { code: 'WB', name: 'West Bengal' },
];

// ─── Industries ───────────────────────────────────────────────────────────────

export const INDUSTRIES: Industry[] = [
  { code: 'IT', name: 'Information Technology' },
  { code: 'ITES', name: 'IT Enabled Services / BPO' },
  { code: 'BFSI', name: 'Banking, Financial Services & Insurance' },
  { code: 'HEALTHCARE', name: 'Healthcare & Pharmaceuticals' },
  { code: 'MANUFACTURING', name: 'Manufacturing' },
  { code: 'RETAIL', name: 'Retail & E-commerce' },
  { code: 'TELECOM', name: 'Telecommunications' },
  { code: 'EDUCATION', name: 'Education & Training' },
  { code: 'MEDIA', name: 'Media & Entertainment' },
  { code: 'HOSPITALITY', name: 'Hospitality & Tourism' },
  { code: 'AUTOMOTIVE', name: 'Automotive' },
  { code: 'CONSTRUCTION', name: 'Construction & Real Estate' },
  { code: 'ENERGY', name: 'Energy & Utilities' },
  { code: 'LOGISTICS', name: 'Logistics & Supply Chain' },
  { code: 'AGRICULTURE', name: 'Agriculture & Food Processing' },
  { code: 'LEGAL', name: 'Legal Services' },
  { code: 'CONSULTING', name: 'Consulting & Professional Services' },
  { code: 'NONPROFIT', name: 'Non-Profit & NGO' },
  { code: 'GOVERNMENT', name: 'Government & Public Sector' },
  { code: 'OTHER', name: 'Other' },
];

// ─── Company Sizes ────────────────────────────────────────────────────────────

export const COMPANY_SIZES: CompanySizeOption[] = [
  { value: '1-10', label: '1-10 employees' },
  { value: '11-50', label: '11-50 employees' },
  { value: '51-200', label: '51-200 employees' },
  { value: '201-500', label: '201-500 employees' },
  { value: '501-1000', label: '501-1000 employees' },
  { value: '1001-5000', label: '1001-5000 employees' },
  { value: '5000+', label: '5000+ employees' },
];

export const FISCAL_YEAR_MONTHS: FiscalYearOption[] = [
  { value: 'january', label: 'January' },
  { value: 'february', label: 'February' },
  { value: 'march', label: 'March' },
  { value: 'april', label: 'April' },
  { value: 'may', label: 'May' },
  { value: 'june', label: 'June' },
  { value: 'july', label: 'July' },
  { value: 'august', label: 'August' },
  { value: 'september', label: 'September' },
  { value: 'october', label: 'October' },
  { value: 'november', label: 'November' },
  { value: 'december', label: 'December' },
];

export const INDIAN_TIMEZONES: TimezoneOption[] = [
  { value: 'Asia/Kolkata', label: 'India Standard Time (IST)' },
  { value: 'Asia/Calcutta', label: 'India Standard Time (Legacy)' },
];

export const DEFAULT_LEAVE_TYPES = [
  {
    leaveCode: 'SL',
    leaveName: 'Sick Leave',
    description: 'Leave for medical reasons. Medical certificate required for 3+ consecutive days.',
    defaultBalance: 12,
    maxAccrual: 12,
    carryForwardLimit: 0,
    carryForwardExpiry: 0,
    encashmentAllowed: false,
    encashmentMaxDays: 0,
    isPaid: true,
    isActive: true,
    applicableGender: 'all',
    minServiceDays: 0,
    documentsRequired: true,
    documentTypes: ['Medical Certificate'],
    accrualType: 'yearly',
    accrualDay: 1,
    minDaysPerRequest: 1,
    maxDaysPerRequest: 7,
    noticeDaysRequired: 0,
    clubbingAllowed: false,
    clubbingRestrictions: ['EL', 'CL'],
    halfDayAllowed: true,
    negativeBalanceAllowed: true,
    negativeBalanceLimit: 3,
    colorCode: '#F44336',
    sortOrder: 2,
  },
  {
    leaveCode: 'CL',
    leaveName: 'Casual Leave',
    description: 'Short duration leave for personal matters. Cannot be carried forward.',
    defaultBalance: 12,
    maxAccrual: 12,
    carryForwardLimit: 0,
    carryForwardExpiry: 0,
    encashmentAllowed: false,
    encashmentMaxDays: 0,
    isPaid: true,
    isActive: true,
    applicableGender: 'all',
    minServiceDays: 0,
    documentsRequired: false,
    documentTypes: [],
    accrualType: 'yearly',
    accrualDay: 1,
    minDaysPerRequest: 0.5,
    maxDaysPerRequest: 3,
    noticeDaysRequired: 1,
    clubbingAllowed: false,
    clubbingRestrictions: ['EL', 'SL'],
    halfDayAllowed: true,
    negativeBalanceAllowed: false,
    negativeBalanceLimit: 0,
    colorCode: '#2196F3',
    sortOrder: 3,
  },
  {
    leaveCode: 'CO',
    leaveName: 'Compensatory Off',
    description: 'Leave granted for working on holidays or weekends. Must be availed within 30 days.',
    defaultBalance: 0,
    maxAccrual: 10,
    carryForwardLimit: 0,
    carryForwardExpiry: 1,
    encashmentAllowed: false,
    encashmentMaxDays: 0,
    isPaid: true,
    isActive: true,
    applicableGender: 'all',
    minServiceDays: 0,
    documentsRequired: true,
    documentTypes: ['Comp-off Approval'],
    accrualType: 'one-time',
    accrualDay: 0,
    minDaysPerRequest: 0.5,
    maxDaysPerRequest: 2,
    noticeDaysRequired: 1,
    clubbingAllowed: true,
    clubbingRestrictions: [],
    halfDayAllowed: true,
    negativeBalanceAllowed: false,
    negativeBalanceLimit: 0,
    colorCode: '#9C27B0',
    sortOrder: 4,
  },
  {
    leaveCode: 'ML',
    leaveName: 'Marriage Leave',
    description: "Leave for employee's own marriage. One-time entitlement.",
    defaultBalance: 5,
    maxAccrual: 5,
    carryForwardLimit: 0,
    carryForwardExpiry: 0,
    encashmentAllowed: false,
    encashmentMaxDays: 0,
    isPaid: true,
    isActive: true,
    applicableGender: 'all',
    minServiceDays: 180,
    documentsRequired: true,
    documentTypes: ['Marriage Invitation', 'Marriage Certificate'],
    accrualType: 'one-time',
    accrualDay: 0,
    minDaysPerRequest: 3,
    maxDaysPerRequest: 5,
    noticeDaysRequired: 30,
    clubbingAllowed: true,
    clubbingRestrictions: [],
    halfDayAllowed: false,
    negativeBalanceAllowed: false,
    negativeBalanceLimit: 0,
    colorCode: '#E91E63',
    sortOrder: 5,
  },
  {
    leaveCode: 'MTL',
    leaveName: 'Maternity Leave',
    description: 'Maternity leave as per Maternity Benefit Act, 2017. 26 weeks for first two children.',
    defaultBalance: 182,
    maxAccrual: 182,
    carryForwardLimit: 0,
    carryForwardExpiry: 0,
    encashmentAllowed: false,
    encashmentMaxDays: 0,
    isPaid: true,
    isActive: true,
    applicableGender: 'female',
    minServiceDays: 80,
    documentsRequired: true,
    documentTypes: ['Medical Certificate', 'Pregnancy Confirmation'],
    accrualType: 'one-time',
    accrualDay: 0,
    minDaysPerRequest: 1,
    maxDaysPerRequest: 182,
    noticeDaysRequired: 30,
    clubbingAllowed: true,
    clubbingRestrictions: [],
    halfDayAllowed: false,
    negativeBalanceAllowed: false,
    negativeBalanceLimit: 0,
    colorCode: '#FF4081',
    sortOrder: 6,
  },
  {
    leaveCode: 'PTL',
    leaveName: 'Paternity Leave',
    description: 'Leave for male employees on childbirth. To be availed within 6 months of childbirth.',
    defaultBalance: 5,
    maxAccrual: 5,
    carryForwardLimit: 0,
    carryForwardExpiry: 0,
    encashmentAllowed: false,
    encashmentMaxDays: 0,
    isPaid: true,
    isActive: true,
    applicableGender: 'male',
    minServiceDays: 180,
    documentsRequired: true,
    documentTypes: ['Birth Certificate'],
    accrualType: 'one-time',
    accrualDay: 0,
    minDaysPerRequest: 1,
    maxDaysPerRequest: 5,
    noticeDaysRequired: 7,
    clubbingAllowed: true,
    clubbingRestrictions: [],
    halfDayAllowed: false,
    negativeBalanceAllowed: false,
    negativeBalanceLimit: 0,
    colorCode: '#3F51B5',
    sortOrder: 7,
  },
  {
    leaveCode: 'BL',
    leaveName: 'Bereavement Leave',
    description: 'Leave due to death of immediate family member.',
    defaultBalance: 5,
    maxAccrual: 5,
    carryForwardLimit: 0,
    carryForwardExpiry: 0,
    encashmentAllowed: false,
    encashmentMaxDays: 0,
    isPaid: true,
    isActive: true,
    applicableGender: 'all',
    minServiceDays: 0,
    documentsRequired: true,
    documentTypes: ['Death Certificate'],
    accrualType: 'one-time',
    accrualDay: 0,
    minDaysPerRequest: 1,
    maxDaysPerRequest: 5,
    noticeDaysRequired: 0,
    clubbingAllowed: true,
    clubbingRestrictions: [],
    halfDayAllowed: false,
    negativeBalanceAllowed: false,
    negativeBalanceLimit: 0,
    colorCode: '#607D8B',
    sortOrder: 8,
  },
  {
    leaveCode: 'STL',
    leaveName: 'Study Leave',
    description: 'Leave for examinations, certifications, or higher studies.',
    defaultBalance: 5,
    maxAccrual: 10,
    carryForwardLimit: 5,
    carryForwardExpiry: 12,
    encashmentAllowed: false,
    encashmentMaxDays: 0,
    isPaid: true,
    isActive: true,
    applicableGender: 'all',
    minServiceDays: 365,
    documentsRequired: true,
    documentTypes: ['Exam Hall Ticket', 'Course Registration'],
    accrualType: 'yearly',
    accrualDay: 1,
    minDaysPerRequest: 1,
    maxDaysPerRequest: 5,
    noticeDaysRequired: 15,
    clubbingAllowed: true,
    clubbingRestrictions: [],
    halfDayAllowed: true,
    negativeBalanceAllowed: false,
    negativeBalanceLimit: 0,
    colorCode: '#00BCD4',
    sortOrder: 9,
  },
  {
    leaveCode: 'SAB',
    leaveName: 'Sabbatical Leave',
    description: 'Extended leave for personal development. Requires management approval.',
    defaultBalance: 0,
    maxAccrual: 90,
    carryForwardLimit: 0,
    carryForwardExpiry: 0,
    encashmentAllowed: false,
    encashmentMaxDays: 0,
    isPaid: false,
    isActive: true,
    applicableGender: 'all',
    minServiceDays: 1825,
    documentsRequired: true,
    documentTypes: ['Sabbatical Plan', 'Management Approval'],
    accrualType: 'one-time',
    accrualDay: 0,
    minDaysPerRequest: 30,
    maxDaysPerRequest: 90,
    noticeDaysRequired: 90,
    clubbingAllowed: false,
    clubbingRestrictions: [],
    halfDayAllowed: false,
    negativeBalanceAllowed: false,
    negativeBalanceLimit: 0,
    colorCode: '#795548',
    sortOrder: 10,
  },
  {
    leaveCode: 'LOP',
    leaveName: 'Loss of Pay',
    description: 'Unpaid leave when other leave balances are exhausted.',
    defaultBalance: 0,
    maxAccrual: 30,
    carryForwardLimit: 0,
    carryForwardExpiry: 0,
    encashmentAllowed: false,
    encashmentMaxDays: 0,
    isPaid: false,
    isActive: true,
    applicableGender: 'all',
    minServiceDays: 0,
    documentsRequired: false,
    documentTypes: [],
    accrualType: 'one-time',
    accrualDay: 0,
    minDaysPerRequest: 0.5,
    maxDaysPerRequest: 30,
    noticeDaysRequired: 0,
    clubbingAllowed: false,
    clubbingRestrictions: [],
    halfDayAllowed: true,
    negativeBalanceAllowed: false,
    negativeBalanceLimit: 0,
    colorCode: '#9E9E9E',
    sortOrder: 11,
  },
  {
    leaveCode: 'RH',
    leaveName: 'Restricted Holiday',
    description: 'Optional holidays that can be availed from a predefined list.',
    defaultBalance: 2,
    maxAccrual: 2,
    carryForwardLimit: 0,
    carryForwardExpiry: 0,
    encashmentAllowed: false,
    encashmentMaxDays: 0,
    isPaid: true,
    isActive: true,
    applicableGender: 'all',
    minServiceDays: 0,
    documentsRequired: false,
    documentTypes: [],
    accrualType: 'yearly',
    accrualDay: 1,
    minDaysPerRequest: 1,
    maxDaysPerRequest: 1,
    noticeDaysRequired: 3,
    clubbingAllowed: true,
    clubbingRestrictions: [],
    halfDayAllowed: false,
    negativeBalanceAllowed: false,
    negativeBalanceLimit: 0,
    colorCode: '#FF9800',
    sortOrder: 12,
  },
  {
    leaveCode: 'WFH',
    leaveName: 'Work From Home',
    description: 'Request to work remotely for the day.',
    defaultBalance: 24,
    maxAccrual: 24,
    carryForwardLimit: 0,
    carryForwardExpiry: 0,
    encashmentAllowed: false,
    encashmentMaxDays: 0,
    isPaid: true,
    isActive: true,
    applicableGender: 'all',
    minServiceDays: 90,
    documentsRequired: false,
    documentTypes: [],
    accrualType: 'yearly',
    accrualDay: 1,
    minDaysPerRequest: 1,
    maxDaysPerRequest: 5,
    noticeDaysRequired: 1,
    clubbingAllowed: false,
    clubbingRestrictions: [],
    halfDayAllowed: true,
    negativeBalanceAllowed: false,
    negativeBalanceLimit: 0,
    colorCode: '#673AB7',
    sortOrder: 13,
  },
  {
    leaveCode: 'ODL',
    leaveName: 'On Duty Leave',
    description: 'Leave for official duties outside office premises.',
    defaultBalance: 0,
    maxAccrual: 30,
    carryForwardLimit: 0,
    carryForwardExpiry: 0,
    encashmentAllowed: false,
    encashmentMaxDays: 0,
    isPaid: true,
    isActive: true,
    applicableGender: 'all',
    minServiceDays: 0,
    documentsRequired: true,
    documentTypes: ['Client Meeting Invite', 'Travel Approval'],
    accrualType: 'one-time',
    accrualDay: 0,
    minDaysPerRequest: 0.5,
    maxDaysPerRequest: 10,
    noticeDaysRequired: 1,
    clubbingAllowed: false,
    clubbingRestrictions: [],
    halfDayAllowed: true,
    negativeBalanceAllowed: false,
    negativeBalanceLimit: 0,
    colorCode: '#009688',
    sortOrder: 14,
  },
  {
    leaveCode: 'ESI',
    leaveName: 'ESI Medical Leave',
    description: 'Extended sick leave covered under ESI scheme.',
    defaultBalance: 0,
    maxAccrual: 91,
    carryForwardLimit: 0,
    carryForwardExpiry: 0,
    encashmentAllowed: false,
    encashmentMaxDays: 0,
    isPaid: true,
    isActive: true,
    applicableGender: 'all',
    minServiceDays: 0,
    documentsRequired: true,
    documentTypes: ['ESI Certificate', 'Medical Report'],
    accrualType: 'one-time',
    accrualDay: 0,
    minDaysPerRequest: 1,
    maxDaysPerRequest: 91,
    noticeDaysRequired: 0,
    clubbingAllowed: false,
    clubbingRestrictions: [],
    halfDayAllowed: false,
    negativeBalanceAllowed: false,
    negativeBalanceLimit: 0,
    colorCode: '#FF5722',
    sortOrder: 15,
  },
  {
    leaveCode: 'SPL',
    leaveName: 'Special Leave',
    description: 'Leave for special circumstances like natural disasters, civic duties, etc.',
    defaultBalance: 0,
    maxAccrual: 10,
    carryForwardLimit: 0,
    carryForwardExpiry: 0,
    encashmentAllowed: false,
    encashmentMaxDays: 0,
    isPaid: true,
    isActive: true,
    applicableGender: 'all',
    minServiceDays: 0,
    documentsRequired: true,
    documentTypes: ['Supporting Documents'],
    accrualType: 'one-time',
    accrualDay: 0,
    minDaysPerRequest: 1,
    maxDaysPerRequest: 10,
    noticeDaysRequired: 0,
    clubbingAllowed: true,
    clubbingRestrictions: [],
    halfDayAllowed: false,
    negativeBalanceAllowed: false,
    negativeBalanceLimit: 0,
    colorCode: '#CDDC39',
    sortOrder: 16,
  },
];

// ─── Constraint Rules (RULE001-RULE013) ───────────────────────────────────────

export const CONSTRAINT_RULES: Omit<ConstraintConfig, 'id' | 'createdAt' | 'updatedAt'>[] = [
  {
    ruleCode: 'RULE001',
    ruleName: 'Minimum Team Availability',
    description: 'At least 50% of team members must be present on any given day',
    ruleType: 'team_availability',
    conditions: [
      { field: 'team_availability_percentage', operator: 'less_than', value: 50 },
    ],
    actions: [
      { type: 'block', message: 'Cannot approve leave as team availability will fall below 50%' },
    ],
    isActive: true,
    priority: 1,
    applicableTo: 'all',
    applicableIds: [],
    effectiveFrom: new Date().toISOString(),
  },
  {
    ruleCode: 'RULE002',
    ruleName: 'No Casual Leave Clubbing',
    description: 'Casual leave cannot be clubbed with other leave types',
    ruleType: 'leave_restriction',
    conditions: [
      { field: 'leave_type', operator: 'equals', value: 'CL' },
      { field: 'adjacent_leave_type', operator: 'not_equals', value: 'none' },
    ],
    actions: [
      { type: 'block', message: 'Casual leave cannot be clubbed with other leaves' },
    ],
    isActive: true,
    priority: 2,
    applicableTo: 'all',
    applicableIds: [],
    effectiveFrom: new Date().toISOString(),
  },
  {
    ruleCode: 'RULE003',
    ruleName: 'Holiday Sandwich Rule',
    description: 'Leaves taken on both sides of a holiday will include the holiday',
    ruleType: 'holiday_adjacency',
    conditions: [
      { field: 'sandwich_scenario', operator: 'equals', value: true },
    ],
    actions: [
      { type: 'warn', message: 'Holiday between leaves will be counted as leave days' },
    ],
    isActive: true,
    priority: 3,
    applicableTo: 'all',
    applicableIds: [],
    effectiveFrom: new Date().toISOString(),
  },
  {
    ruleCode: 'RULE004',
    ruleName: 'Probation Leave Restriction',
    description: 'Employees on probation can only avail sick leave and LOP',
    ruleType: 'probation_restriction',
    conditions: [
      { field: 'employment_status', operator: 'equals', value: 'probation' },
      { field: 'leave_type', operator: 'not_in', value: ['SL', 'LOP'] },
    ],
    actions: [
      { type: 'block', message: 'Only Sick Leave and LOP are allowed during probation' },
    ],
    isActive: true,
    priority: 1,
    applicableTo: 'all',
    applicableIds: [],
    effectiveFrom: new Date().toISOString(),
  },
  {
    ruleCode: 'RULE005',
    ruleName: 'Notice Period Leave Restriction',
    description: 'Employees in notice period cannot avail earned leave',
    ruleType: 'notice_period',
    conditions: [
      { field: 'employment_status', operator: 'equals', value: 'notice_period' },
      { field: 'leave_type', operator: 'equals', value: 'EL' },
    ],
    actions: [
      { type: 'block', message: 'Earned leave cannot be availed during notice period' },
    ],
    isActive: true,
    priority: 1,
    applicableTo: 'all',
    applicableIds: [],
    effectiveFrom: new Date().toISOString(),
  },
  {
    ruleCode: 'RULE006',
    ruleName: 'Maximum Consecutive Days',
    description: 'Maximum consecutive leave days allowed is 15 (excluding approved long leaves)',
    ruleType: 'maximum_consecutive',
    conditions: [
      { field: 'consecutive_days', operator: 'greater_than', value: 15 },
      { field: 'leave_type', operator: 'not_in', value: ['MTL', 'SAB', 'ESI'] },
    ],
    actions: [
      {
        type: 'require_approval',
        message: 'Leave exceeding 15 days requires special approval',
        notifyRoles: ['HR', 'Department Head'],
      },
    ],
    isActive: true,
    priority: 4,
    applicableTo: 'all',
    applicableIds: [],
    effectiveFrom: new Date().toISOString(),
  },
  {
    ruleCode: 'RULE007',
    ruleName: 'Medical Certificate Requirement',
    description: 'Sick leave of 3 or more days requires medical certificate',
    ruleType: 'document_requirement',
    conditions: [
      { field: 'leave_type', operator: 'equals', value: 'SL' },
      { field: 'duration_days', operator: 'greater_than', value: 2 },
    ],
    actions: [
      { type: 'require_document', message: 'Medical certificate is mandatory for sick leave of 3+ days' },
    ],
    isActive: true,
    priority: 2,
    applicableTo: 'all',
    applicableIds: [],
    effectiveFrom: new Date().toISOString(),
  },
  {
    ruleCode: 'RULE008',
    ruleName: 'Blackout Period - Year End',
    description: 'No leaves allowed during year-end closing (March 25-31)',
    ruleType: 'blackout_period',
    conditions: [
      { field: 'leave_date_range', operator: 'between', value: ['03-25', '03-31'] },
    ],
    actions: [
      {
        type: 'require_approval',
        message: 'Year-end period requires special approval for leaves',
        notifyRoles: ['Finance Head', 'HR'],
      },
    ],
    isActive: true,
    priority: 1,
    applicableTo: 'department',
    applicableIds: ['FINANCE', 'ACCOUNTS'],
    effectiveFrom: new Date().toISOString(),
  },
  {
    ruleCode: 'RULE009',
    ruleName: 'Minimum Gap Between Leaves',
    description: 'Minimum 7 days gap required between two casual leave instances',
    ruleType: 'minimum_gap',
    conditions: [
      { field: 'leave_type', operator: 'equals', value: 'CL' },
      { field: 'days_since_last_leave', operator: 'less_than', value: 7 },
    ],
    actions: [
      { type: 'warn', message: 'Recommended to maintain 7 days gap between casual leaves' },
    ],
    isActive: true,
    priority: 5,
    applicableTo: 'all',
    applicableIds: [],
    effectiveFrom: new Date().toISOString(),
  },
  {
    ruleCode: 'RULE010',
    ruleName: 'Overlap Prevention',
    description: 'Prevent overlapping leave requests',
    ruleType: 'overlap_prevention',
    conditions: [
      { field: 'has_overlap', operator: 'equals', value: true },
    ],
    actions: [
      { type: 'block', message: 'You already have an approved or pending leave for these dates' },
    ],
    isActive: true,
    priority: 1,
    applicableTo: 'all',
    applicableIds: [],
    effectiveFrom: new Date().toISOString(),
  },
  {
    ruleCode: 'RULE011',
    ruleName: 'Insufficient Balance Check',
    description: 'Block leave requests that exceed available balance',
    ruleType: 'balance_check',
    conditions: [
      { field: 'requested_days', operator: 'greater_than', value: 0 },
      { field: 'available_balance', operator: 'less_than', value: 0 },
    ],
    actions: [
      { type: 'block', message: 'Insufficient leave balance. Please select a different leave type.' },
    ],
    isActive: true,
    priority: 1,
    applicableTo: 'all',
    applicableIds: [],
    effectiveFrom: new Date().toISOString(),
  },
  {
    ruleCode: 'RULE012',
    ruleName: 'Comp-off Expiry',
    description: 'Comp-off must be availed within 30 days of earning',
    ruleType: 'leave_restriction',
    conditions: [
      { field: 'leave_type', operator: 'equals', value: 'CO' },
      { field: 'days_since_earned', operator: 'greater_than', value: 30 },
    ],
    actions: [
      { type: 'warn', message: 'Comp-off is expiring soon. Please avail within 30 days of earning.' },
    ],
    isActive: true,
    priority: 3,
    applicableTo: 'all',
    applicableIds: [],
    effectiveFrom: new Date().toISOString(),
  },
  {
    ruleCode: 'RULE013',
    ruleName: 'Advance Leave Application',
    description: 'Earned leave must be applied at least 15 days in advance',
    ruleType: 'leave_restriction',
    conditions: [
      { field: 'leave_type', operator: 'equals', value: 'EL' },
      { field: 'advance_days', operator: 'less_than', value: 15 },
    ],
    actions: [
      { type: 'warn', message: 'Earned leave should be applied at least 15 days in advance' },
    ],
    isActive: true,
    priority: 4,
    applicableTo: 'all',
    applicableIds: [],
    effectiveFrom: new Date().toISOString(),
  },
];

// ─── Default Roles ────────────────────────────────────────────────────────────

export const DEFAULT_ROLES: Omit<RoleConfig, 'id' | 'createdAt' | 'updatedAt'>[] = [
  {
    roleName: 'Super Admin',
    roleCode: 'SUPER_ADMIN',
    description: 'Full system access with all permissions',
    permissions: [
      { module: 'all', actions: ['create', 'read', 'update', 'delete', 'approve', 'export'] },
    ],
    isSystem: true,
    isActive: true,
    hierarchy: 1,
  },
  {
    roleName: 'Company Owner',
    roleCode: 'COMPANY_OWNER',
    description: 'Company-level administrative access',
    permissions: [
      { module: 'company_settings', actions: ['create', 'read', 'update', 'delete'] },
      { module: 'employees', actions: ['create', 'read', 'update', 'delete', 'approve'] },
      { module: 'leaves', actions: ['create', 'read', 'update', 'delete', 'approve', 'export'] },
      { module: 'reports', actions: ['read', 'export'] },
      { module: 'payroll', actions: ['create', 'read', 'update', 'approve', 'export'] },
    ],
    isSystem: true,
    isActive: true,
    hierarchy: 2,
  },
  {
    roleName: 'HR Manager',
    roleCode: 'HR_MANAGER',
    description: 'Human Resources management access',
    permissions: [
      { module: 'employees', actions: ['create', 'read', 'update', 'approve'] },
      { module: 'leaves', actions: ['create', 'read', 'update', 'approve', 'export'] },
      { module: 'attendance', actions: ['read', 'update', 'export'] },
      { module: 'reports', actions: ['read', 'export'] },
      { module: 'leave_policies', actions: ['create', 'read', 'update'] },
    ],
    isSystem: true,
    isActive: true,
    hierarchy: 3,
  },
  {
    roleName: 'Department Head',
    roleCode: 'DEPT_HEAD',
    description: 'Department-level management access',
    permissions: [
      { module: 'employees', actions: ['read'] },
      { module: 'leaves', actions: ['read', 'approve'] },
      { module: 'attendance', actions: ['read'] },
      { module: 'reports', actions: ['read', 'export'] },
    ],
    isSystem: true,
    isActive: true,
    hierarchy: 4,
  },
  {
    roleName: 'Team Lead',
    roleCode: 'TEAM_LEAD',
    description: 'Team-level management access',
    permissions: [
      { module: 'employees', actions: ['read'] },
      { module: 'leaves', actions: ['read', 'approve'] },
      { module: 'attendance', actions: ['read'] },
    ],
    isSystem: true,
    isActive: true,
    hierarchy: 5,
  },
  {
    roleName: 'Finance Manager',
    roleCode: 'FINANCE_MANAGER',
    description: 'Finance and payroll access',
    permissions: [
      { module: 'payroll', actions: ['create', 'read', 'update', 'approve', 'export'] },
      { module: 'reports', actions: ['read', 'export'] },
      { module: 'leaves', actions: ['read', 'export'] },
    ],
    isSystem: true,
    isActive: true,
    hierarchy: 4,
  },
  {
    roleName: 'Employee',
    roleCode: 'EMPLOYEE',
    description: 'Standard employee access',
    permissions: [
      { module: 'leaves', actions: ['create', 'read'] },
      { module: 'attendance', actions: ['read'] },
      { module: 'profile', actions: ['read', 'update'] },
    ],
    isSystem: true,
    isActive: true,
    hierarchy: 10,
  },
];

// ─── Onboarding Step Labels ───────────────────────────────────────────────────

export const ONBOARDING_STEP_LABELS: Record<number, string> = {
  1: 'Company Profile',
  2: 'Role Configuration',
  3: 'Leave Types',
  4: 'Constraints & Rules',
  5: 'Approval Workflow',
  6: 'Holiday Calendar',
  7: 'Work Schedule',
  8: 'Payroll Defaults',
  9: 'Complete Setup',
};

// ─── Onboarding Step Descriptions ─────────────────────────────────────────────

export const ONBOARDING_STEP_DESCRIPTIONS: Record<number, string> = {
  1: 'Set up your company details and primary contact information',
  2: 'Configure user roles and permissions for your organization',
  3: 'Define leave types and their policies',
  4: 'Set up leave constraints and business rules',
  5: 'Configure approval workflows for leave requests',
  6: 'Set up company holidays and restricted holidays',
  7: 'Define working days and shift timings',
  8: 'Configure payroll and statutory compliance settings',
  9: 'Review and complete your company setup',
};

// ─── Days of Week ─────────────────────────────────────────────────────────────

export const DAYS_OF_WEEK = [
  { value: 0, label: 'Sunday', short: 'Sun' },
  { value: 1, label: 'Monday', short: 'Mon' },
  { value: 2, label: 'Tuesday', short: 'Tue' },
  { value: 3, label: 'Wednesday', short: 'Wed' },
  { value: 4, label: 'Thursday', short: 'Thu' },
  { value: 5, label: 'Friday', short: 'Fri' },
  { value: 6, label: 'Saturday', short: 'Sat' },
] as const;

// ─── Payroll Cycles ───────────────────────────────────────────────────────────

export const PAYROLL_CYCLES = [
  { value: 'weekly', label: 'Weekly' },
  { value: 'bi-weekly', label: 'Bi-Weekly' },
  { value: 'monthly', label: 'Monthly' },
] as const;

// ─── Tax Regimes ──────────────────────────────────────────────────────────────

export const TAX_REGIMES = [
  { value: 'old', label: 'Old Tax Regime' },
  { value: 'new', label: 'New Tax Regime' },
  { value: 'employee_choice', label: 'Employee Choice' },
] as const;

// ─── LOP Deduction Basis ──────────────────────────────────────────────────────

export const LOP_DEDUCTION_BASIS = [
  { value: 'calendar_days', label: 'Calendar Days (Actual days in month)' },
  { value: 'working_days', label: 'Working Days (Excluding weekends/holidays)' },
  { value: 'fixed_30', label: 'Fixed 30 Days' },
] as const;
